Item.create!(name: 'Canned Goods')
Item.create!(name: 'Shirt')
Item.create!(name: 'Pants')
Item.create!(name: 'Paper Towel')
Item.create!(name: 'Water Bottle')
Item.create!(name: 'Blanket')
Item.create!(name: 'Shoes')
Item.create!(name: 'Sleeping Bag')
Item.create!(name: 'Toilet Paper')
Item.create!(name: 'Soft Drinks')
Item.create!(name: 'Basic Phone')
Item.create!(name: 'Smart Phone')
Item.create!(name: 'Tablet')
Item.create!(name: 'Misc Electronic Items')
Item.create!(name: 'Misc Paper Products')
Item.create!(name: 'Misc Clothing Items')
Item.create!(name: 'Misc Non-Perishable Foods')
Item.create!(name: 'Toiletries')
Item.create!(name: 'First Aid Items')
Item.create!(name: 'Diapers')
Item.create!(name: 'Games/ Toys')
Item.create!(name: 'Books')
Item.create!(name: 'School Supplies')
puts 'Items added'
